### ISSUE TITLE
How do you feel about incorporating Reactive Programming?

### ISSUE THREAD

**Issue by OfTheDelmer** [mjdesa/foie#2]
https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

https://github.com/Reactive-Extensions/RxJS

https://baconjs.github.io/

https://www.youtube.com/watch?v=XE692Clb5LU

**Comment by boichee** [comment]
I have to say, this is a really interesting idea.

I may go ahead and start writing up some examples of how this could be used in the code that's already been put together.

B
